### ISSUE TITLE
Cursor start point needs to adjust to nametag width.

### ISSUE THREAD

**Issue by PedantiCat** [onfe/Picto#1]

**Comment by onfe** [comment]
There are a few weird things here:
- It's currently not possible to have a text size based on purely component width, so currently cursor positions can have some error due to the scrollbar.
- The time it takes for the browser to finish painting and sizing components needs to be accounted for before measuring the name-tag. This isn't ideal.

`setTimeout({}, 50);` seems to allow the browser enough time to finish painting.
