### ISSUE TITLE
iOS doesn't:

### ISSUE THREAD

**Issue by TheTeaCat** [onfe/Picto#3]
- Draw
 - Display text in progress
 - Generally just work

**Comment by onfe** [comment]
iOS 13 with the latest Safari (incl. OSX) works fine, but earlier versions of Safari do *not* support pointer events.

Requires polyfill or similar.

**Comment by freddyheppell** [comment]
Tested it now, the only issue I found was that upon clicking the keyboard button, the keyboard opens over the top of the drawing area and you have to scroll down to view it.

I think this is because ios safari won't move the page in response to js initiated focuses. Were you to be actually focusing on a real element it'd work fine.

Probably the best solution is to just scroll to the bottom of the page after focusing.
