### ISSUE TITLE
No way to unset theme cookie

### ISSUE THREAD

**Issue by freddyheppell** [onfe/Picto#89]
If you set a theme preference there's no way to set it back to following the system theme without manually deleting the cookie.

**Comment by TheTeaCat** [comment]
2c86277bcd1d5e5eae72566648cda4c5c674ed22 is a partial fix but I believe it would also be appreciated if it immediately responded to changes in prefers-color-scheme as opposed to requiring a reload. Still working on this...

**Comment by onfe** [comment]
Considering that `prefers-color-scheme` changes so rarely, it's probably fine as-is.

**Comment by TheTeaCat** [comment]
I've had to introduce a "system default" setting in 98863e668c328dd355920401f62ce359d6ed4ae4 because if the prefers-color-scheme being equal to the current theme is assumed as meaning the user has no preference, the following issue occurs:

1. The user has prefers-color-scheme set to light, and changes the theme within Picto to dark (so this is stored in a cookie).
2. The user's prefers-color-scheme automatically switches to dark because they have it timed to daylight hours, making it is the same as the current Picto theme, so the cookie is deleted.
3. The user visits Picto again tomorrow during daylight hours, when their prefers-color-scheme is set to light, and the theme is light again! Big disaster

**Comment by TheTeaCat** [comment]
I believe as of d6389f96690b48f5e7162407b3a953aedf18e217 this is closed, awaiting merge to master.
